# security/secret-management/vault-config.yml
vault:
  uri: http://localhost:8200
  token: s.1234567890abcdef # Example token for Vault
  secrets:
    db-username: postgres
    db-password: password
    mongo-username: root
    mongo-password: example
