---
server:
  port: 8005
spring:
  application:
    name: loan-service
  datasource:
    url: jdbc:h2:mem:loandb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://abrar2030:abrar2030@localhost:8001/eureka/
  instance:
    prefer-ip-address: true