---
server:
  port: 8006
spring:
  application:
    name: notification-service
  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_email_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:h2:mem:reportingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://abrar2030:abrar2030@localhost:8001/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com.finova: INFO
