---
server:
  port: 8002
spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8001/eureka/}
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false
jwt:
  secret: ${JWT_SECRET:changeme}
  expiration-time: ${JWT_EXPIRATION_TIME:3600000}
