---
services:
  eureka-server:
    build:
      context: ./backend/eureka-server
      dockerfile: Dockerfile
    image: abrar2030/backend:eureka-server
    container_name: eureka-server
    ports:
      - "8001:8001"
    networks:
      - fintech-network

  api-gateway:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
    image: abrar2030/backend:api-gateway
    container_name: api-gateway
    ports:
      - "8002:8002"
    depends_on:
      - eureka-server
      - account-management
      - transaction
      - notification
      - user-profile
    networks:
      - fintech-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8001/eureka/
      - JWT_SECRET=your_jwt_secret_here

  account-management:
    build:
      context: ./backend/account-management
      dockerfile: Dockerfile
    image: abrar2030/backend:account-management
    container_name: account-management
    ports:
      - "8003:8003"
    depends_on:
      - eureka-server
    networks:
      - fintech-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8001/eureka/

  transaction:
    build:
      context: ./backend/transaction
      dockerfile: Dockerfile
    image: abrar2030/backend:transaction
    container_name: transaction
    ports:
      - "8004:8004"
    depends_on:
      - eureka-server
      - account-management
    networks:
      - fintech-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8001/eureka/
      - JWT_SECRET=your_jwt_secret_here

  notification:
    build:
      context: ./backend/notification
      dockerfile: Dockerfile
    image: abrar2030/backend:notification
    container_name: notification
    ports:
      - "8005:8005"
    depends_on:
      - eureka-server
    networks:
      - fintech-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8001/eureka/
      - JWT_SECRET=your_jwt_secret_here

  user-profile:
    build:
      context: ./backend/user-profile
      dockerfile: Dockerfile
    image: abrar2030/backend:user-profile
    container_name: user-profile
    ports:
      - "8006:8006"
    depends_on:
      - eureka-server
    networks:
      - fintech-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8001/eureka/

  finovabank-frontend:
    build:
      context: ./frontend/finovabank-frontend
      dockerfile: Dockerfile
    image: abrar2030/frontend:finovabank-frontend
    container_name: finovabank-frontend
    ports:
      - "3001:80"
    depends_on:
      - api-gateway
    networks:
      - fintech-network
    environment:
      - REACT_APP_API_BASE_URL=http://api-gateway:8002

networks:
  fintech-network:
    driver: bridge
