---
version: '3.8'
services:
  eureka-server:
    build:
      context: ./account-management
      dockerfile: Dockerfile
    image: abrar2030/finovabank:eureka-server
    container_name: eureka-server
    ports:
      - "8001:8001"
    networks:
      - finovabank-network
    environment:
      - EUREKA_SERVER_PORT=8001
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    image: abrar2030/finovabank:api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
      - account-management
      - transaction-service
      - notification-service
      - loan-management
      - risk-assessment
      - savings-goals
    networks:
      - finovabank-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8001/eureka/
      - API_GATEWAY_PORT=8080
  account-management:
    build:
      context: ./account-management
      dockerfile: Dockerfile
    image: abrar2030/finovabank:account-management
    container_name: account-management
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
    networks:
      - finovabank-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8001/eureka/
      - ACCOUNT_MANAGEMENT_PORT=8081
  transaction-service:
    build:
      context: ./transaction-service
      dockerfile: Dockerfile
    image: abrar2030/finovabank:transaction-service
    container_name: transaction-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - account-management
    networks:
      - finovabank-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8001/eureka/
      - TRANSACTION_SERVICE_PORT=8082
  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    image: abrar2030/finovabank:notification-service
    container_name: notification-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
    networks:
      - finovabank-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8001/eureka/
      - NOTIFICATION_SERVICE_PORT=8083
  loan-management:
    build:
      context: ./loan-management
      dockerfile: Dockerfile
    image: abrar2030/finovabank:loan-management
    container_name: loan-management
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
    networks:
      - finovabank-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8001/eureka/
      - LOAN_MANAGEMENT_PORT=8084
  compliance:
    build:
      context: ./compliance
      dockerfile: Dockerfile
    image: abrar2030/finovabank:compliance
    container_name: compliance-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
    networks:
      - finovabank-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8001/eureka/
      - COMPLIANCE_SERVICE_PORT=8085
  reporting:
    build:
      context: ./reporting
      dockerfile: Dockerfile
    image: abrar2030/finovabank:reporting
    container_name: reporting-service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
    networks:
      - finovabank-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8001/eureka/
      - REPORTING_SERVICE_PORT=8086
  risk-assessment:
    build:
      context: ./risk-assessment
      dockerfile: Dockerfile
    image: abrar2030/finovabank:risk-assessment
    container_name: risk-assessment-service
    ports:
      - "8087:8087"
    depends_on:
      - eureka-server
    networks:
      - finovabank-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8001/eureka/
      - RISK_ASSESSMENT_SERVICE_PORT=8087
  savings-goals:
    build:
      context: ./savings-goals
      dockerfile: Dockerfile
    image: abrar2030/finovabank:savings-goals
    container_name: savings-goals-service
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
    networks:
      - finovabank-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8001/eureka/
      - SAVINGS_GOALS_SERVICE_PORT=8088
  frontend:
    build:
      context: ./frontend/frontend
      dockerfile: Dockerfile
    image: abrar2030/finovabank:frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    networks:
      - finovabank-network
    environment:
      - REACT_APP_API_BASE_URL=http://api-gateway:8080
networks:
  finovabank-network:
    driver: bridge
