# infrastructure/secrets/secrets.yml
apiVersion: v1
kind: Secret
metadata:
  name: finova-secrets
  namespace: finova-namespace
type: Opaque
data:
  postgres-username: cG9zdGdyZXM=
  postgres-password: cGFzc3dvcmQ=
  mongo-username: cm9vdA==
  mongo-password: ZXhhbXBsZQ==
