# security/encryption/enc-config.yml
encryption:
  algorithm: AES
  keysize: 256
  key: "bXlTZWNyZXRLZXkxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=" # Example AES key (base64 encoded)
  iv: "MTIzNDU2Nzg5MDEyMzQ1Ng==" # Example IV (base64 encoded)
