---
account:
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5433/accountdb
transaction:
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5434/transactiondb
loan:
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5435/loandb
savings:
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5436/savingsdb
risk:
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5437/riskdb
compliance:
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5438/compliancedb
notification:
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5439/notificationdb
reporting:
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5440/reportingdb
