---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loan-management
  labels:
    app: loan-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loan-management
  template:
    metadata:
      labels:
        app: loan-management
    spec:
      containers:
        - name: loan-management
          image: abrar2030/finovabackend:loan-management
          ports:
            - containerPort: 8090
