---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-assessment-service
  labels:
    app: risk-assessment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk-assessment-service
  template:
    metadata:
      labels:
        app: risk-assessment-service
    spec:
      containers:
        - name: risk-assessment-service
          image: abrar2030/finovabackend:risk-assessment
          ports:
            - containerPort: 8092
