---

# templates/deployment-risk-assessment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-assessment-service
  labels:
    app: risk-assessment-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: risk-assessment-service
  template:
    metadata:
      labels:
        app: risk-assessment-service
    spec:
      containers:
        - name: risk-assessment-service
          image: {{ .Values.image.repository }}/risk-assessment-service:{{ .Values.image.tag }}
          ports:
            - containerPort: 8092
