---

# templates/deployment-finovabank-frontend.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: finovabank-frontend
  labels:
    {{- include "finovabank.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: finovabank-frontend
  template:
    metadata:
      labels:
        app: finovabank-frontend
    spec:
      containers:
        - name: finovabank-frontend
          image: {{ .Values.image.repository }}/finovabank-frontend:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          env:
            - name: API_BASE_URL
              value: {{ .Values.environment.API_BASE_URL }}
