---

# templates/deployment-savings-goals.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: savings-goals-service
  labels:
    app: savings-goals-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: savings-goals-service
  template:
    metadata:
      labels:
        app: savings-goals-service
    spec:
      containers:
        - name: savings-goals-service
          image: {{ .Values.image.repository }}/savings-goals-service:{{ .Values.image.tag }}
          ports:
            - containerPort: 8094
