---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: savings-goals-service
  labels:
    app: savings-goals-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: savings-goals-service
  template:
    metadata:
      labels:
        app: savings-goals-service
    spec:
      containers:
        - name: savings-goals-service
          image: abrar2030/finovabackend:savings-goals
          ports:
            - containerPort: 8094
