---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: compliance-service
  labels:
    app: compliance-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compliance-service
  template:
    metadata:
      labels:
        app: compliance-service
    spec:
      containers:
        - name: compliance-service
          image: abrar2030/finovabackend:compliance
          ports:
            - containerPort: 8091
