---

# templates/service-frontend.yaml
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    {{- include "finovabank.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: frontend
