{{- range $serviceName, $service := .Values.services }}
{{- if $service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $serviceName }}
    {{- include "finovabank.labels" $ | nindent 4 }}
spec:
  type: {{ $service.type | default $.Values.service.type }}
  ports:
    - port: {{ $service.port }}
      targetPort: {{ $service.port }}
      protocol: TCP
  selector:
    app: {{ $serviceName }}
{{- end }}
{{- end }}

