# service-account-management.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: account-management
  labels:
    app: account-management
spec:
  type: ClusterIP
  ports:
    - port: 8095
      targetPort: 8095
  selector:
    app: account-management
