---

# templates/service-api-gateway.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    {{- include "finovabank.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8002
      targetPort: 8002
  selector:
    app: api-gateway
