---

# templates/service-eureka-server.yaml
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  labels:
    {{- include "finovabank.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: eureka-server