---

apiVersion: v1
kind: Service
metadata:
  name: compliance-service
  labels:
    app: compliance-service
spec:
  type: {? {.Values.service.type: ''} : ''}
  ports:
    - port: 8091
      targetPort: 8091
  selector:
    app: compliance-service
