---
apiVersion: v1
kind: Service
metadata:
  name: savings-goals-service
  labels:
    app: savings-goals-service
spec:
  type: ClusterIP
  ports:
    - port: 8094
      targetPort: 8094
  selector:
    app: savings-goals-service
