---
apiVersion: v1
kind: Service
metadata:
  name: loan-management
  labels:
    app: loan-management
spec:
  type: ClusterIP
  ports:
    - port: 8090
      targetPort: 8090
  selector:
    app: loan-management
