---
apiVersion: v1
kind: Service
metadata:
  name: reporting-service
  labels:
    app: reporting-service
spec:
  type: ClusterIP
  ports:
    - port: 8093
      targetPort: 8093
  selector:
    app: reporting-service
