---
apiVersion: v1
kind: Service
metadata:
  name: risk-assessment-service
  labels:
    app: risk-assessment-service
spec:
  type: ClusterIP
  ports:
    - port: 8092
      targetPort: 8092
  selector:
    app: risk-assessment-service
