---

replicaCount: 1
image:
  repository: abrar2030/finovabank
  tag: "latest"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8002
environment:
  API_BASE_URL: "http://api-gateway:8002"
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi
