---
server:
  port: 8007
spring:
  application:
    name: reporting-service
  datasource:
    url: jdbc:h2:mem:reportingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8001/eureka/
