---
server:
  port: 8003
spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:h2:mem:transactiondb 
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
  h2:
    console:
      enabled: true 
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8001/eureka/
