---
server:
  port: 8002
spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://abrar2030:abrar2030@localhost:8001/eureka/
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false
jwt:
  secret: mySuperSecretKey1234567890 
  expiration-time: 3600000 
